name: spotlight
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - pandas>=2.0.0
    - numpy>=1.24.0
    - nltk>=3.8
    - rank-bm25>=0.2.2
    - sentence-transformers>=2.2.0
    - scikit-learn>=1.3.0
    - streamlit>=1.25.0
    - tabulate>=0.9.0
    - torch>=2.0.0
